### ISSUE TITLE
help....

### ISSUE THREAD

**Issue by Mabastcity** [itsnebulalol/palera1n#19]
when i try to add this; git checkout 254b42f067893ce32a10e8a99b2dfbec2149cb54 

i get this;  git checkout 254b42f067893ce32a10e8a99b2dfbec2149cb54
Note: switching to '254b42f067893ce32a10e8a99b2dfbec2149cb54'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 254b42f only include config if we have config
  

what should i do?  linux ubuntu

**Comment by kristenlc** [comment]
you posted this issue in the wrong github repo, this error is from a different [repo](https://github.com/kristenlc/palera1n-High-Sierra)
the video says to use a different [repo](https://github.com/kristenlc/palera1n-High-Sierra) and the link is in the video description
it links to nebula to credit nebula for the making of the jailbreak
but it says right below to use the other repo to follow the video instructions

this is normal behavior of `git clone --recursive https://github.com/tihmstar/libgeneral.git`
it is only after that command is done that you continue following the video instruction
```
cd libgeneral
git checkout 254b42f067893ce32a10e8a99b2dfbec2149cb54
./autogen.sh
sudo rm -f /usr/local/lib/libgeneral*
make clean
sudo make install
ls /usr/local/lib/libgeneral*
cd ..
```
this will install the libgeneral dependency which is required for the script on that other repo to work
i cut the video right after i hit git clone and cut back after it was done cloning because it took a while
then you must also run `pip3 install pyimg4` and continue to follow video instructions

if you could close this issue and reopen it here with the same content on the other repo i think nebula would appreciate it

**Comment by Mabastcity** [comment]
I'm sorry but my English is not too good just can u tell step by step what should i do?

**Comment by itsnebulalol** [comment]
first, you should only use that fork if you’re on high sierra

second, the readme is pretty in-depth
